### YamlMime:QSharpType
uid: microsoft.quantum.canon.decomposeintotimestepsca
name: DecomposeIntoTimeStepsCA
type: function
namespace: Microsoft.Quantum.Canon
summary: Devuelve una operación que implementa el integrador Trotter – Suzuki para una operación determinada.
syntax: "function DecomposeIntoTimeStepsCA ((nSteps : Int, op : ((Int, Double, 'T) => Unit is Adj + Ctl)), trotterOrder : Int) : ((Double, 'T) => Unit is Adj + Ctl)"
references: >-
  We use the implementation in


  - [ *D. W. Berry, G. Ahokas, R. Cleve, B. C. Sanders* ](https://arxiv.org/abs/quant-ph/0508139)
input:
  content: "((nSteps: int, op: ((int, Double, ' t) = > Unit es ADJ + CTL)), trotterOrder: int)"
  types:
  - name: nSteps
    isPrimitive: true
    uid: Int
  - name: operador
    isOperation: true
    input:
      types:
      - isPrimitive: true
        uid: Int
      - isPrimitive: true
        uid: Double
      - uid: "'T"
        isLocal: true
    output:
      types:
      - isPrimitive: true
        uid: Unit
    functors:
    - Adjoint
    - Controlled
  - name: trotterOrder
    summary: >-
      Selecciona el orden del integrador Trotter – Suzuki que se va a usar.

      Actualmente se admiten los pedidos 1 y 2.
    isPrimitive: true
    uid: Int
output:
  content: ((Double, ' t) = > unidad es ADJ + CTL)
  types:
  - summary: Devuelve una unitario que implementa el integrador Trotter – Suzuki, donde el primer parámetro `Double` es el tamaño del paso de integración y el segundo parámetro es el destino sobre el que se actuó.
    isOperation: true
    input:
      types:
      - isPrimitive: true
        uid: Double
      - uid: "'T"
        isLocal: true
    output:
      types:
      - isPrimitive: true
        uid: Unit
    functors:
    - Adjoint
    - Controlled
typeParameters:
- uid: "'T"
  summary: Tipo en el que debe actuar cada paso de tiempo; Normalmente, `Qubit[]` o `Qubit`.
ms.openlocfilehash: 328db9b314320c724cf03adb19ee59d63a33e56e
ms.sourcegitcommit: 8becfb03eb60ba205c670a634ff4daa8071bcd06
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 10/30/2019
ms.locfileid: "73067839"
