### YamlMime:QSharpType
uid: microsoft.quantum.canon.compose
name: Compose
type: function
namespace: microsoft.quantum.canon
summary: >-
  Devuelve la composición de dos funciones.


  Dadas dos funciones $f $ y $g $, devuelve una nueva función que representa $f \circ g $.
syntax: "function Compose (outer : ('U -> 'V), inner : ('T -> 'U)) : ('T -> 'V)"
input:
  content: "(outer : ('U -> 'V), inner : ('T -> 'U))"
  types:
  - name: outer
    summary: Segunda función que se va a aplicar.
    isFunction: true
    input:
      types:
      - uid: "'U"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
  - name: inner
    summary: La primera función que se va a aplicar.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'U"
        isLocal: true
output:
  content: ('T -> 'V)
  types:
  - summary: Una nueva función $h $ tal que para todas las entradas $x $, $f (g (x)) = h (x) $.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
typeParameters:
- uid: "'T"
  summary: Tipo de entrada de la primera función que se va a aplicar.
- uid: "'U"
  summary: El tipo de salida de la primera función que se va a aplicar y el tipo de entrada de la segunda función que se va a aplicar.
- uid: "'V"
  summary: Tipo de salida de la segunda función que se va a aplicar.
metadata:
  ms.openlocfilehash: e62937fd42cb4067ca7a7947cac29a9ef539da6c
  ms.sourcegitcommit: d6ac6f4345be0dd68f1bcd944f44b08e7a3cf346
  ms.translationtype: MT
  ms.contentlocale: es-ES
  ms.lasthandoff: 09/02/2020
  ms.locfileid: "89356752"
